services:
  mysql9:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password_file
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    secrets:
      - mysql_root_password_file

secrets:
  mysql_root_password_file:
    file: ./secrets/mysql_root_password
