services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_initdb_root_password_file
    volumes:
      - ./data/:/data/db/

secrets:
  mongo_initdb_root_password_file:
    file: ./secrets/mongo_initdb_root_password